name: Build Python Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install requests colorama fake_useragent pymongo python-dotenv
      
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py
      
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/main.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install requests colorama fake_useragent pymongo python-dotenv
      
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py
      
      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/main
