name: Build Python Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Сначала очистим старые артефакты
  cleanup-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'
          skip-tags: true
          skip-recent: 5

  # После очистки, приступаем к сборке
  build-windows:
    needs: cleanup-artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install requests colorama fake_useragent pymongo python-dotenv
      
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py
      
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/main.exe
          retention-days: 1

  build-macos:
    needs: cleanup-artifacts
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install requests colorama fake_useragent pymongo python-dotenv
      
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile main.py
      
      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/main
          retention-days: 1
